### ISSUE TITLE
Warning: The upload provider "strapi-provider-upload-cloudflare-2" doesn't implement the uploadStream function. Strapi will fallback on the upload method. Some performance issues may occur.

### ISSUE THREAD

**Issue by ricky11** [mettle-studio/strapi-provider-upload-cloudflare-2#7]
When running npm run develop, we get the following warning :

Warning: The upload provider "strapi-provider-upload-cloudflare-2" doesn't implement the uploadStream function. Strapi will fallback on the upload method. Some performance issues may occur.

We created the api key with ACCOUNT CLOUDFLARE IMAGES & ACCOUNT STREAMS with edit more in the cloudflare dashboard.

**Comment by savvas-mettle** [comment]
closed on https://github.com/mettle-studio/strapi-provider-upload-cloudflare-2/pull/9
