### ISSUE TITLE
Video uploading to CloudFlare is broken.

### ISSUE THREAD

**Issue by sahaviev** [mettle-studio/strapi-provider-upload-cloudflare-2#8]
Hello!

First of all I would like to say a lot of thanks and appreciation for developing this open source plugin.
It is working perfectly with images, but unfortunately, it seems video uploading to Cloudflare is broken.

I think it is implemented using this example: https://developers.cloudflare.com/stream/uploading-videos/upload-video-file/#nodejs-example

For some reason it now returns 2 responses and current implementation **onAfterResponse** resolves Promise before uploading is finished. https://github.com/mettle-studio/strapi-provider-upload-cloudflare-2/blob/main/lib/uploadVideo.js#L29

As possible quick fix solution I would suggest saving **onAfterResponse** result to closure variable and resolve video uploading promise on **onSuccess** event.
<img width="545" alt="image" src="https://user-images.githubusercontent.com/1573252/193365021-c8738285-7067-4af3-bb56-2d26b42b5d20.png">

It might be I made somewhere incorrect configuration. Let's understand the problem together, please.

Thanks!

**Comment by savvas-mettle** [comment]
You are right, fixed on https://github.com/mettle-studio/strapi-provider-upload-cloudflare-2/pull/9
